In [10]:
from os import mkdir

import duplicates
from IPython.display import Image, display
import DataLoader as dl
import pandas as pd


dataloader = dl.DataLoader()

movies_df = dataloader.movies_df
actors_df = dataloader.actors_df
countries_df = dataloader.countries_df
crew_df = dataloader.crew_df
genres_df = dataloader.genres_df
languages_df = dataloader.languages_df
posters_df = dataloader.posters_df
releases_df = dataloader.releases_df
studios_df = dataloader.studios_df
themes_df = dataloader.themes_df
rotten_tomatoes_df = dataloader.rotten_tomatoes_df
oscar_awards_df = dataloader.oscar_awards_df

movies_df

name    date  \
id                                                   
1000001                             Barbie  2023.0   
1000002                           Parasite  2019.0   
1000003  Everything Everywhere All at Once  2022.0   
1000004                         Fight Club  1999.0   
1000005                         La La Land  2016.0   
...                                    ...     ...   
1941593                                 神笛     NaN   
1941594                      蟲極道蜜団子抗争編 壱ノ巻     NaN   
1941595                      蟲極道蜜団子抗争編 弐ノ巻     NaN   
1941596                                 重生     NaN   
1941597                             青ひげ公の城     NaN   

                                                  tagline  \
id                                                          
1000001                  She's everything. He's just Ken.   
1000002                       Act like you own the place.   
1000003  The universe is so much bigger than you realize.   
1000004                           Mischief. Mayhem. Soap.   
1000005                    Here's to the fools who dream.   
...                                                   ...   
1941593                                               NaN   
1941594                                               NaN   
1941595                                               NaN   
1941596                                               NaN   
1941597                                               NaN   

                                               description  minute  rating  
id                                                                          
1000001  Barbie and Ken are having the time of their li...   114.0    3.86  
1000002  All unemployed, Ki-taek's family takes peculia...   133.0    4.56  
1000003  An aging Chinese immigrant is swept up in an i...   140.0    4.30  
1000004  A ticking-time-bomb insomniac and a slippery s...   139.0    4.27  
1000005  Mia, an aspiring actress, serves lattes to mov...   129.0    4.09  
...                                                    ...     ...     ...  
1941593                                                NaN     NaN     NaN  
1941594  Shinjuku forest at night. In the sap taverns o...    30.0     NaN  
1941595  The city that never sleeps, where insects gath...    30.0     NaN  
1941596  In a world where order has broken down, darkne...     NaN     NaN  
1941597                                                NaN   130.0     NaN  

[941597 rows x 6 columns]

In [11]:
print("Movie columns:" , movies_df.columns)
print("Actors columns:" , actors_df.columns)
print("Countries columns:" , countries_df.columns)
print("Crew columns:" , crew_df.columns)
print("Genres columns:" , genres_df.columns)
print("Languages columns:" , languages_df.columns)
print("Posters columns:" , posters_df.columns)
print("Release columns:" , releases_df.columns)
print("Studios columns:" , studios_df.columns)
print("Themes columns:" , themes_df.columns)
print("Oscar columns:" , oscar_awards_df.columns)
print("Rotten columns:" , rotten_tomatoes_df.columns)

Movie columns: Index(['name', 'date', 'tagline', 'description', 'minute', 'rating'], dtype='object')
Actors columns: Index(['name', 'role'], dtype='object')
Countries columns: Index(['country'], dtype='object')
Crew columns: Index(['role', 'name'], dtype='object')
Genres columns: Index(['genre'], dtype='object')
Languages columns: Index(['type', 'language'], dtype='object')
Posters columns: Index(['link'], dtype='object')
Release columns: Index(['country', 'date', 'type', 'rating'], dtype='object')
Studios columns: Index(['studio'], dtype='object')
Themes columns: Index(['theme'], dtype='object')
Oscar columns: Index(['year_film', 'year_ceremony', 'ceremony', 'category', 'name', 'film',
       'winner'],
      dtype='object')
Rotten columns: Index(['rotten_tomatoes_link', 'movie_title', 'critic_name', 'top_critic',
       'publisher_name', 'review_type', 'review_score', 'review_date',
       'review_content'],
      dtype='object')


# Data Cleaning
## Removing or replacing all the data that are not compliant with the dataset
### Dataset types:


fetch and cast the data to their correct type

In [12]:
movies_df.dtypes

name            object
date           float64
tagline         object
description     object
minute         float64
rating         float64
dtype: object

In [13]:
movies_df['name'] = movies_df['name'].astype(pd.StringDtype())
movies_df['tagline'] = movies_df['tagline'].astype(pd.StringDtype())
movies_df['description'] = movies_df['description'].astype(pd.StringDtype())
movies_df['date'] = movies_df['date'].astype('Int64')

In [14]:
movies_df.dtypes

name           string[python]
date                    Int64
tagline        string[python]
description    string[python]
minute                float64
rating                float64
dtype: object

In [15]:
actors_df.dtypes

name    object
role    object
dtype: object

In [16]:
actors_df['name'] = actors_df['name'].astype(pd.StringDtype())
actors_df['role'] = actors_df['role'].astype(pd.StringDtype())

In [17]:
countries_df.dtypes

country    object
dtype: object

In [18]:
countries_df['country'] = countries_df['country'].astype(pd.StringDtype())

In [19]:
crew_df.dtypes

role    object
name    object
dtype: object

In [20]:
crew_df['role'] = crew_df['role'].astype(pd.StringDtype())
crew_df['name'] = crew_df['name'].astype(pd.StringDtype())

In [21]:
genres_df.dtypes

genre    object
dtype: object

In [22]:
genres_df['genre'] = genres_df['genre'].astype(pd.StringDtype())

In [23]:
languages_df.dtypes

type        object
language    object
dtype: object

In [24]:
languages_df['type'] = languages_df['type'].astype(pd.StringDtype())
languages_df['language'] = languages_df['language'].astype(pd.StringDtype())

In [25]:
posters_df.dtypes

link    object
dtype: object

In [26]:
posters_df['link'] = posters_df['link'].astype(pd.StringDtype())

In [27]:
releases_df.dtypes

country    object
date       object
type       object
rating     object
dtype: object

In [28]:
releases_df['country'] = releases_df['country'].astype(pd.StringDtype())
releases_df['date'] = releases_df['date'].astype(pd.StringDtype()) #todo: change to date type
releases_df['type'] = releases_df['type'].astype(pd.StringDtype())
releases_df['rating'] = releases_df['rating'].astype(pd.StringDtype())

In [29]:
studios_df.dtypes

studio    object
dtype: object

In [30]:
studios_df['studio'] = studios_df['studio'].astype(pd.StringDtype())

In [31]:
themes_df.dtypes

theme    object
dtype: object

In [32]:
themes_df['theme'] = themes_df['theme'].astype(pd.StringDtype())

fetching the movies without a name

In [33]:
movies_df[movies_df['name'].isna()]

name  date tagline  \
id                            
1287515  <NA>  2015    <NA>   
1617643  <NA>  <NA>    <NA>   
1646521  <NA>  2008    <NA>   
1648186  <NA>  <NA>    <NA>   
1720295  <NA>  <NA>    <NA>   
1725370  <NA>  <NA>    <NA>   
1741482  <NA>  <NA>    <NA>   
1840338  <NA>  <NA>    <NA>   
1883229  <NA>  <NA>    <NA>   
1894772  <NA>  <NA>    <NA>   

                                               description  minute  rating  
id                                                                          
1287515  NONE is a short film that explores the balance...     4.0     NaN  
1617643                                               <NA>     NaN     NaN  
1646521                                               <NA>     NaN     NaN  
1648186                                               <NA>     NaN     NaN  
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN  
1725370                                               <NA>     NaN     NaN  
1741482                                               <NA>    90.0     NaN  
1840338                                               <NA>     NaN     NaN  
1883229                                               <NA>     NaN     NaN  
1894772                                               <NA>     NaN     NaN

### Movies:

by joining the subset of the movie without a name we can ensure that no reference are lost during the process (no other part of the dataset actually contain some data about those movies)

In [34]:
movies_na_subset = pd.DataFrame(movies_df[movies_df['name'].isna()])

#movies_na_subset join actors
movies_na_subset.join(actors_df, on='id', lsuffix='_movies', rsuffix='_actors')

name_movies  date tagline  \
id                                  
1287515        <NA>  2015    <NA>   
1617643        <NA>  <NA>    <NA>   
1646521        <NA>  2008    <NA>   
1648186        <NA>  <NA>    <NA>   
1720295        <NA>  <NA>    <NA>   
1725370        <NA>  <NA>    <NA>   
1741482        <NA>  <NA>    <NA>   
1840338        <NA>  <NA>    <NA>   
1883229        <NA>  <NA>    <NA>   
1894772        <NA>  <NA>    <NA>   

                                               description  minute  rating  \
id                                                                           
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1617643                                               <NA>     NaN     NaN   
1646521                                               <NA>     NaN     NaN   
1648186                                               <NA>     NaN     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN   
1725370                                               <NA>     NaN     NaN   
1741482                                               <NA>    90.0     NaN   
1840338                                               <NA>     NaN     NaN   
1883229                                               <NA>     NaN     NaN   
1894772                                               <NA>     NaN     NaN   

         name_actors  role  
id                          
1287515         <NA>  <NA>  
1617643         <NA>  <NA>  
1646521  Catherine R  Self  
1648186         <NA>  <NA>  
1720295         <NA>  <NA>  
1725370         <NA>  <NA>  
1741482         <NA>  <NA>  
1840338         <NA>  <NA>  
1883229         <NA>  <NA>  
1894772         <NA>  <NA>

In [35]:
#movies_na_subset join countries
movies_na_subset.join(countries_df, on='id', lsuffix='_movies', rsuffix='_countries')

name  date tagline  \
id                            
1287515  <NA>  2015    <NA>   
1617643  <NA>  <NA>    <NA>   
1646521  <NA>  2008    <NA>   
1648186  <NA>  <NA>    <NA>   
1720295  <NA>  <NA>    <NA>   
1725370  <NA>  <NA>    <NA>   
1741482  <NA>  <NA>    <NA>   
1840338  <NA>  <NA>    <NA>   
1883229  <NA>  <NA>    <NA>   
1894772  <NA>  <NA>    <NA>   

                                               description  minute  rating  \
id                                                                           
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1617643                                               <NA>     NaN     NaN   
1646521                                               <NA>     NaN     NaN   
1648186                                               <NA>     NaN     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN   
1725370                                               <NA>     NaN     NaN   
1741482                                               <NA>    90.0     NaN   
1840338                                               <NA>     NaN     NaN   
1883229                                               <NA>     NaN     NaN   
1894772                                               <NA>     NaN     NaN   

        country  
id               
1287515    <NA>  
1617643    <NA>  
1646521     USA  
1648186    <NA>  
1720295    <NA>  
1725370    <NA>  
1741482    <NA>  
1840338    <NA>  
1883229    <NA>  
1894772    <NA>

In [36]:
#movies_na_subset join crew
movies_na_subset.join(crew_df, on='id', lsuffix='_movies', rsuffix='_crew')

name_movies  date tagline  \
id                                  
1287515        <NA>  2015    <NA>   
1287515        <NA>  2015    <NA>   
1617643        <NA>  <NA>    <NA>   
1646521        <NA>  2008    <NA>   
1648186        <NA>  <NA>    <NA>   
1720295        <NA>  <NA>    <NA>   
1725370        <NA>  <NA>    <NA>   
1741482        <NA>  <NA>    <NA>   
1840338        <NA>  <NA>    <NA>   
1883229        <NA>  <NA>    <NA>   
1894772        <NA>  <NA>    <NA>   

                                               description  minute  rating  \
id                                                                           
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1617643                                               <NA>     NaN     NaN   
1646521                                               <NA>     NaN     NaN   
1648186                                               <NA>     NaN     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN   
1725370                                               <NA>     NaN     NaN   
1741482                                               <NA>    90.0     NaN   
1840338                                               <NA>     NaN     NaN   
1883229                                               <NA>     NaN     NaN   
1894772                                               <NA>     NaN     NaN   

             role         name_crew  
id                                   
1287515  Director         Ash Thorp  
1287515  Composer  Ben Lukas Boysen  
1617643      <NA>              <NA>  
1646521  Director  Giovanni De Nava  
1648186      <NA>              <NA>  
1720295      <NA>              <NA>  
1725370      <NA>              <NA>  
1741482      <NA>              <NA>  
1840338      <NA>              <NA>  
1883229      <NA>              <NA>  
1894772      <NA>              <NA>

In [37]:
#movies_na_subset join genres
movies_na_subset.join(genres_df, on='id', lsuffix='_movies', rsuffix='_genres')

name  date tagline  \
id                            
1287515  <NA>  2015    <NA>   
1617643  <NA>  <NA>    <NA>   
1646521  <NA>  2008    <NA>   
1648186  <NA>  <NA>    <NA>   
1720295  <NA>  <NA>    <NA>   
1725370  <NA>  <NA>    <NA>   
1741482  <NA>  <NA>    <NA>   
1840338  <NA>  <NA>    <NA>   
1883229  <NA>  <NA>    <NA>   
1894772  <NA>  <NA>    <NA>   

                                               description  minute  rating  \
id                                                                           
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1617643                                               <NA>     NaN     NaN   
1646521                                               <NA>     NaN     NaN   
1648186                                               <NA>     NaN     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN   
1725370                                               <NA>     NaN     NaN   
1741482                                               <NA>    90.0     NaN   
1840338                                               <NA>     NaN     NaN   
1883229                                               <NA>     NaN     NaN   
1894772                                               <NA>     NaN     NaN   

               genre  
id                    
1287515    Animation  
1617643  Documentary  
1646521  Documentary  
1648186     Thriller  
1720295         <NA>  
1725370         <NA>  
1741482         <NA>  
1840338         <NA>  
1883229         <NA>  
1894772         <NA>

In [38]:
#movies_na_subset join languages
movies_na_subset.join(languages_df, on='id', lsuffix='_movies', rsuffix='_languages')

name  date tagline  \
id                            
1287515  <NA>  2015    <NA>   
1617643  <NA>  <NA>    <NA>   
1646521  <NA>  2008    <NA>   
1648186  <NA>  <NA>    <NA>   
1720295  <NA>  <NA>    <NA>   
1725370  <NA>  <NA>    <NA>   
1741482  <NA>  <NA>    <NA>   
1840338  <NA>  <NA>    <NA>   
1883229  <NA>  <NA>    <NA>   
1894772  <NA>  <NA>    <NA>   

                                               description  minute  rating  \
id                                                                           
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1617643                                               <NA>     NaN     NaN   
1646521                                               <NA>     NaN     NaN   
1648186                                               <NA>     NaN     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN   
1725370                                               <NA>     NaN     NaN   
1741482                                               <NA>    90.0     NaN   
1840338                                               <NA>     NaN     NaN   
1883229                                               <NA>     NaN     NaN   
1894772                                               <NA>     NaN     NaN   

             type language  
id                          
1287515      <NA>     <NA>  
1617643  Language  English  
1646521  Language  English  
1648186  Language  English  
1720295  Language  Burmese  
1725370  Language  English  
1741482  Language  English  
1840338  Language  English  
1883229  Language  English  
1894772  Language  English

In [39]:
#movies_na_subset join posters
movies_na_subset.join(posters_df, on='id', lsuffix='_movies', rsuffix='_posters')

name  date tagline  \
id                            
1287515  <NA>  2015    <NA>   
1617643  <NA>  <NA>    <NA>   
1646521  <NA>  2008    <NA>   
1648186  <NA>  <NA>    <NA>   
1720295  <NA>  <NA>    <NA>   
1725370  <NA>  <NA>    <NA>   
1741482  <NA>  <NA>    <NA>   
1840338  <NA>  <NA>    <NA>   
1883229  <NA>  <NA>    <NA>   
1894772  <NA>  <NA>    <NA>   

                                               description  minute  rating  \
id                                                                           
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1617643                                               <NA>     NaN     NaN   
1646521                                               <NA>     NaN     NaN   
1648186                                               <NA>     NaN     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN   
1725370                                               <NA>     NaN     NaN   
1741482                                               <NA>    90.0     NaN   
1840338                                               <NA>     NaN     NaN   
1883229                                               <NA>     NaN     NaN   
1894772                                               <NA>     NaN     NaN   

                                                      link  
id                                                          
1287515  https://a.ltrbxd.com/resized/film-poster/4/4/7...  
1617643                                               <NA>  
1646521  https://a.ltrbxd.com/resized/film-poster/1/0/1...  
1648186                                               <NA>  
1720295                                               <NA>  
1725370                                               <NA>  
1741482  https://a.ltrbxd.com/resized/film-poster/6/5/6...  
1840338  https://a.ltrbxd.com/resized/film-poster/5/8/4...  
1883229  https://a.ltrbxd.com/resized/film-poster/7/4/1...  
1894772  https://a.ltrbxd.com/resized/film-poster/1/0/4...

In [40]:
#movies_na_subset join releases
movies_na_subset.join(releases_df, on='id', lsuffix='_movies', rsuffix='_releases')

name  date_movies tagline  \
id                                   
1287515  <NA>         2015    <NA>   
1617643  <NA>         <NA>    <NA>   
1646521  <NA>         2008    <NA>   
1648186  <NA>         <NA>    <NA>   
1720295  <NA>         <NA>    <NA>   
1725370  <NA>         <NA>    <NA>   
1741482  <NA>         <NA>    <NA>   
1840338  <NA>         <NA>    <NA>   
1883229  <NA>         <NA>    <NA>   
1894772  <NA>         <NA>    <NA>   

                                               description  minute  \
id                                                                   
1287515  NONE is a short film that explores the balance...     4.0   
1617643                                               <NA>     NaN   
1646521                                               <NA>     NaN   
1648186                                               <NA>     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0   
1725370                                               <NA>     NaN   
1741482                                               <NA>    90.0   
1840338                                               <NA>     NaN   
1883229                                               <NA>     NaN   
1894772                                               <NA>     NaN   

         rating_movies country date_releases        type rating_releases  
id                                                                        
1287515            NaN     USA    2015-01-01  Theatrical            <NA>  
1617643            NaN    <NA>          <NA>        <NA>            <NA>  
1646521            NaN     USA    2008-03-02  Theatrical              PG  
1648186            NaN    <NA>          <NA>        <NA>            <NA>  
1720295            NaN    <NA>          <NA>        <NA>            <NA>  
1725370            NaN    <NA>          <NA>        <NA>            <NA>  
1741482            NaN    <NA>          <NA>        <NA>            <NA>  
1840338            NaN    <NA>          <NA>        <NA>            <NA>  
1883229            NaN    <NA>          <NA>        <NA>            <NA>  
1894772            NaN    <NA>          <NA>        <NA>            <NA>

In [41]:
#movies_na_subset join studios
movies_na_subset.join(studios_df, on='id', lsuffix='_movies', rsuffix='_studios')

name  date tagline  \
id                            
1287515  <NA>  2015    <NA>   
1617643  <NA>  <NA>    <NA>   
1646521  <NA>  2008    <NA>   
1648186  <NA>  <NA>    <NA>   
1720295  <NA>  <NA>    <NA>   
1725370  <NA>  <NA>    <NA>   
1741482  <NA>  <NA>    <NA>   
1840338  <NA>  <NA>    <NA>   
1883229  <NA>  <NA>    <NA>   
1894772  <NA>  <NA>    <NA>   

                                               description  minute  rating  \
id                                                                           
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1617643                                               <NA>     NaN     NaN   
1646521                                               <NA>     NaN     NaN   
1648186                                               <NA>     NaN     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN   
1725370                                               <NA>     NaN     NaN   
1741482                                               <NA>    90.0     NaN   
1840338                                               <NA>     NaN     NaN   
1883229                                               <NA>     NaN     NaN   
1894772                                               <NA>     NaN     NaN   

        studio  
id              
1287515   <NA>  
1617643   <NA>  
1646521   <NA>  
1648186   <NA>  
1720295   <NA>  
1725370   <NA>  
1741482   <NA>  
1840338   <NA>  
1883229   <NA>  
1894772   <NA>

In [42]:
#movies_na_subset join themes
movies_na_subset.join(themes_df, on='id', lsuffix='_movies', rsuffix='_themes')

name  date tagline  \
id                            
1287515  <NA>  2015    <NA>   
1617643  <NA>  <NA>    <NA>   
1646521  <NA>  2008    <NA>   
1648186  <NA>  <NA>    <NA>   
1720295  <NA>  <NA>    <NA>   
1725370  <NA>  <NA>    <NA>   
1741482  <NA>  <NA>    <NA>   
1840338  <NA>  <NA>    <NA>   
1883229  <NA>  <NA>    <NA>   
1894772  <NA>  <NA>    <NA>   

                                               description  minute  rating  \
id                                                                           
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1617643                                               <NA>     NaN     NaN   
1646521                                               <NA>     NaN     NaN   
1648186                                               <NA>     NaN     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN   
1725370                                               <NA>     NaN     NaN   
1741482                                               <NA>    90.0     NaN   
1840338                                               <NA>     NaN     NaN   
1883229                                               <NA>     NaN     NaN   
1894772                                               <NA>     NaN     NaN   

        theme  
id             
1287515  <NA>  
1617643  <NA>  
1646521  <NA>  
1648186  <NA>  
1720295  <NA>  
1725370  <NA>  
1741482  <NA>  
1840338  <NA>  
1883229  <NA>  
1894772  <NA>

## Looking at the joined table it is possible to make some correction at the dataset

movie with id 1287515: looking at the description and at the poster and after a quick search on internet it is possible to evaluate that the name of the Movie is ***NONE***, no it is possible to update the name in the table

In [43]:
display(Image(url=posters_df['link'][1287515], width=200, height=300))

In [44]:
movies_df.loc[1287515,'name'] = "NONE"

movie with id: 1720295 looking at the description and after a quick search on internet it is possible to evaluate that the name of the Movie is ***Memorandum of Softness Green***

In [45]:
movies_df.loc[1720295, 'name'] = "Memorandum of Softness Green"

movie with id 1741482: looking at the poster it is possible to name the movie: ***Sweethurt*** but this time the record for this movie is a duplicate (see 1254818) so all the reference will be deleted

In [46]:
movies_df.drop(1720295)
actors_df.drop(1720295, errors='ignore')
countries_df.drop(1720295, errors='ignore')
crew_df.drop(1720295, errors='ignore')
genres_df.drop(1720295, errors='ignore')
languages_df.drop(1720295, errors='ignore')
posters_df.drop(1720295, errors='ignore')
releases_df.drop(1720295, errors='ignore')
studios_df.drop(1720295, errors='ignore')
themes_df.drop(1720295, errors='ignore')
print()

movie with id 1840338: looking at the poster it is possible to name the movie: ***The Find*** and the director is ***Daniel Dahlstrom***

In [47]:
display(Image(url=posters_df['link'][1840338], width=200, height=300))

In [48]:
movies_df.loc[1840338,'name'] = "The Find"
crew_df.loc[1840338] = ['Director'] + ["Daniel Dahlstrom"]

movies with id: 1617643,1646521,1648186,1725370,1741482,1883229,1894772 will be deleted along with every reference

In [49]:
#multiple execution of this block could bring some errors
movies_df = movies_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772]).copy()
actors_df = actors_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
countries_df = countries_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
crew_df = crew_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
genres_df = genres_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
languages_df = languages_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
posters_df = posters_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
releases_df = releases_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
studios_df = studios_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
themes_df = themes_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
print()

In [50]:
movies_df[movies_df['name'].isna()]

Empty DataFrame
Columns: [name, date, tagline, description, minute, rating]
Index: []

in the dataset there are movies with same name, and description but different minute and rating. it's not safe to delete duplicate that are not equal in every column of the dataset because a movies may have been produced in different versions

In [51]:
movies_df.loc[movies_df.duplicated(subset=['name','date','description','minute','rating'])]

name  date  \
id                                           
1073819              Better Than Sex  2000   
1073820                     Amoklauf  1994   
1073822         Still Working 9 to 5  2022   
1073823  Power On: The Story of Xbox  2021   
1073824            Crossing the Line  2006   
...                              ...   ...   
1940234                         Medo  2023   
1940448   Riina - Le verità nascoste  2018   
1940456                 Yen Ching 燕京  2018   
1940593              Happy Birthday!  2013   
1941150                     Extraños  <NA>   

                                                  tagline  \
id                                                          
1073819            3 days in the life of a 1 night stand.   
1073820                                              <NA>   
1073822                                              <NA>   
1073823  Four gamers. One idea. And a billion dollar bet.   
1073824                                              <NA>   
...                                                   ...   
1940234                                              <NA>   
1940448                                              <NA>   
1940456                                              <NA>   
1940593                                              <NA>   
1941150                                              <NA>   

                                               description  minute  rating  
id                                                                          
1073819  After a one-night stand a couple is faced with...    84.0    3.24  
1073820  A nameless waiter spends his days sitting arou...    65.0     NaN  
1073822  Examines the 40-year evolution of gender inequ...    95.0     NaN  
1073823  Xbox almost didn't happen. Find out why in thi...     NaN    3.61  
1073824  In 1962, a U.S. soldier sent to guard the peac...    94.0    3.44  
...                                                    ...     ...     ...  
1940234                                               <NA>     4.0     NaN  
1940448                                               <NA>    45.0     NaN  
1940456  An intergenerational dilemma between immigrant...    64.0     NaN  
1940593  'Misery' doesn't like 'company' -- but 'compan...    20.0     NaN  
1941150                                               <NA>     NaN     NaN  

[4115 rows x 6 columns]

removing the duplicates

In [52]:
movies_df = movies_df.loc[~movies_df.duplicated(subset=['name','date','description','minute','rating'])].copy()
number_of_duplicate = movies_df.duplicated(subset=['name','date','description','minute','rating']).sum()
print("Number of duplicates:" ,number_of_duplicate)

Number of duplicates: 0


### Actors

In [53]:
actors_df

name                 role
id                                             
1000001      Margot Robbie               Barbie
1000001       Ryan Gosling                  Ken
1000001    America Ferrera               Gloria
1000001  Ariana Greenblatt                Sasha
1000001           Issa Rae               Barbie
...                    ...                  ...
1941596            Marc Ma            Ba Cai/巴莱
1941596                线雨轩              Tata/塔塔
1941596       Jiang Yixuan  Zuo Yila（Zoila）/佐伊拉
1941597     Hiroshi Mikami                 <NA>
1941597      Keiko Oginome                 <NA>

[5798449 rows x 2 columns]

In [54]:
actors_df.loc[actors_df['name'].isna()]

name            role
id                           
1443629  <NA>            <NA>
1469981  <NA>            Self
1474958  <NA>  Cinematography
1773264  <NA>            <NA>

there is no way to reach these names

In [55]:
actors_df = actors_df.loc[~actors_df['name'].isna()].copy()
actors_df

name                 role
id                                             
1000001      Margot Robbie               Barbie
1000001       Ryan Gosling                  Ken
1000001    America Ferrera               Gloria
1000001  Ariana Greenblatt                Sasha
1000001           Issa Rae               Barbie
...                    ...                  ...
1941596            Marc Ma            Ba Cai/巴莱
1941596                线雨轩              Tata/塔塔
1941596       Jiang Yixuan  Zuo Yila（Zoila）/佐伊拉
1941597     Hiroshi Mikami                 <NA>
1941597      Keiko Oginome                 <NA>

[5798445 rows x 2 columns]

In [56]:
actors_df.duplicated(subset=['name']).count()

np.int64(5798445)

In [57]:
countries_df

country
id                  
1000001           UK
1000001          USA
1000002  South Korea
1000003          USA
1000004      Germany
...              ...
1941593        China
1941594          USA
1941595          USA
1941596        China
1941597        Japan

[693475 rows x 1 columns]

In [58]:
countries_df.loc[countries_df['country'].isna()]

Empty DataFrame
Columns: [country]
Index: []

countries have a lot of duplicates because each movie could have been  recorded in one or more countries, there is no need to delete duplicates is this case

In [59]:
crew_df

role                  name
id                                           
1000001        Director          Greta Gerwig
1000001        Producer          Tom Ackerley
1000001        Producer         Margot Robbie
1000001        Producer        Robbie Brenner
1000001        Producer          David Heyman
...                 ...                   ...
1941596          Editor  Eric Kwong Chi-Leung
1941596  Cinematography             Kenny Tse
1941596        Composer                   胡小欧
1941596  Costume design           Kenneth Yee
1840338        Director      Daniel Dahlstrom

[4720183 rows x 2 columns]

In [60]:
crew_df.loc[crew_df['name'].isna()]

role  name
id                   
1859397  Writer  <NA>

In [61]:
crew_df = crew_df[~crew_df['name'].isna()].copy()

dataframe crew have a lot of duplicates because each crew member participated in multiple movies

In [62]:
crew_df.loc[crew_df.duplicated()]

role                  name
id                                            
1000005  Camera operator           Ari Robbins
1000005           Stunts          Danny Downey
1000005            Sound           Ai-Ling Lee
1000005            Sound         Dan O'Connell
1000005      Hairstyling       Fríða Aradóttir
...                  ...                   ...
1941596          Casting                   线雨轩
1941596           Editor  Eric Kwong Chi-Leung
1941596   Cinematography             Kenny Tse
1941596   Costume design           Kenneth Yee
1840338         Director      Daniel Dahlstrom

[2907770 rows x 2 columns]

In [63]:
genres_df

genre
id                
1000001     Comedy
1000001  Adventure
1000002     Comedy
1000002   Thriller
1000002      Drama
...            ...
1941563      Drama
1941566      Crime
1941569      Crime
1941596     Action
1941596      Crime

[1046846 rows x 1 columns]

In [64]:
genres_df.loc[genres_df['genre'].isna()]

Empty DataFrame
Columns: [genre]
Index: []

In [65]:
genres_df.loc[genres_df.duplicated()]

genre
id                
1000002     Comedy
1000003  Adventure
1000003     Comedy
1000004      Drama
1000005      Drama
...            ...
1941563      Drama
1941566      Crime
1941569      Crime
1941596     Action
1941596      Crime

[1046827 rows x 1 columns]

In [66]:
languages_df

type  language
id                                 
1000001          Language   English
1000002  Primary language    Korean
1000002   Spoken language   English
1000002   Spoken language    German
1000002   Spoken language    Korean
...                   ...       ...
1941593          Language   Chinese
1941594          Language   English
1941595          Language   English
1941596          Language   Chinese
1941597          Language  Japanese

[1038755 rows x 2 columns]

In [67]:
languages_df.loc[languages_df[['type','language']].isna().all(axis=1)]

Empty DataFrame
Columns: [type, language]
Index: []

In [68]:
posters_df

link
id                                                        
1000001  https://a.ltrbxd.com/resized/film-poster/2/7/7...
1000002  https://a.ltrbxd.com/resized/film-poster/4/2/6...
1000003  https://a.ltrbxd.com/resized/film-poster/4/7/4...
1000004  https://a.ltrbxd.com/resized/film-poster/5/1/5...
1000005  https://a.ltrbxd.com/resized/film-poster/2/4/0...
...                                                    ...
1941593                                               <NA>
1941594                                               <NA>
1941595  https://a.ltrbxd.com/resized/film-poster/1/1/8...
1941596  https://a.ltrbxd.com/resized/film-poster/1/1/8...
1941597                                               <NA>

[941590 rows x 1 columns]

In [69]:
posters_df.loc[posters_df['link'].isna()]

link
id           
1014019  <NA>
1015381  <NA>
1016468  <NA>
1018453  <NA>
1027194  <NA>
...       ...
1941590  <NA>
1941591  <NA>
1941593  <NA>
1941594  <NA>
1941597  <NA>

[180709 rows x 1 columns]

in this case removing the <NA> values will keep the data a bit cleaner


In [70]:
posters_df = posters_df[~posters_df['link'].isna()].copy()

In [71]:
posters_df.loc[posters_df.duplicated()]

link
id                                                        
1073819  https://a.ltrbxd.com/resized/film-poster/3/4/5...
1073820  https://a.ltrbxd.com/resized/film-poster/3/1/0...
1073822  https://a.ltrbxd.com/resized/film-poster/7/6/0...
1073823  https://a.ltrbxd.com/resized/film-poster/8/2/2...
1073824  https://a.ltrbxd.com/resized/film-poster/3/7/4...
...                                                    ...
1829507  https://a.ltrbxd.com/resized/film-poster/1/1/4...
1864503  https://a.ltrbxd.com/resized/film-poster/1/1/8...
1897229  https://a.ltrbxd.com/resized/film-poster/1/0/1...
1897230  https://a.ltrbxd.com/resized/film-poster/1/0/1...
1934309  https://a.ltrbxd.com/resized/film-poster/1/0/4...

[1286 rows x 1 columns]

removing duplicated posters

In [72]:
posters_df = posters_df[~posters_df['link'].duplicated()].copy()

In [73]:
releases_df

country        date        type rating
id                                               
1000001    Andorra  2023-07-21  Theatrical   <NA>
1000001  Argentina  2023-07-20  Theatrical    ATP
1000001  Australia  2023-07-19  Theatrical     PG
1000001  Australia  2023-10-01     Digital     PG
1000001    Austria  2023-07-20  Theatrical   <NA>
...            ...         ...         ...    ...
1940967        USA  1909-01-01  Theatrical   <NA>
1940968     Sweden  1908-11-11  Theatrical   <NA>
1940969     France  1902-01-01  Theatrical   <NA>
1940970     France  1902-01-01  Theatrical   <NA>
1940971     France  1902-01-01  Theatrical   <NA>

[1332781 rows x 4 columns]

In [74]:
releases_df.loc[releases_df[['country','date','type','rating']].isna().all(axis=1)]

Empty DataFrame
Columns: [country, date, type, rating]
Index: []

checking duplicates in each movie, adding index as helper column

In [75]:
releases_df['index'] = releases_df.index
releases_df.loc[releases_df.duplicated(subset=['index','country','date','type'])]

Empty DataFrame
Columns: [country, date, type, rating, index]
Index: []

removing index helper column

In [76]:
releases_df.drop(['index'], axis=1)

country        date        type rating
id                                               
1000001    Andorra  2023-07-21  Theatrical   <NA>
1000001  Argentina  2023-07-20  Theatrical    ATP
1000001  Australia  2023-07-19  Theatrical     PG
1000001  Australia  2023-10-01     Digital     PG
1000001    Austria  2023-07-20  Theatrical   <NA>
...            ...         ...         ...    ...
1940967        USA  1909-01-01  Theatrical   <NA>
1940968     Sweden  1908-11-11  Theatrical   <NA>
1940969     France  1902-01-01  Theatrical   <NA>
1940970     France  1902-01-01  Theatrical   <NA>
1940971     France  1902-01-01  Theatrical   <NA>

[1332781 rows x 4 columns]

In [68]:
studios_df

studio
id                              
1000001  LuckyChap Entertainment
1000001             Heyday Films
1000001           NB/GG Pictures
1000001                   Mattel
1000001    Warner Bros. Pictures
...                          ...
1941596               上海猫眼影业有限公司
1941596            坏小子（北京）传媒有限公司
1941596         亚太国影（重庆）文化传媒有限公司
1941596               凤凰传奇影业有限公司
1941596             无双（深圳）影业有限公司

[679283 rows x 1 columns]

In [69]:
studios_df.loc[studios_df['studio'].isna()]

studio
id            
1259717   <NA>
1350206   <NA>
1450762   <NA>
1565428   <NA>
1579904   <NA>
1590891   <NA>
1605792   <NA>
1648488   <NA>
1706513   <NA>
1934958   <NA>

in this case removing the <NA> values will keep the data a bit cleaner

In [70]:
studios_df = studios_df[~studios_df['studio'].isna()].copy()

In [71]:
studios_df['index'] = studios_df.index
studios_df.loc[studios_df.duplicated(subset=['index','studio'])]

studio    index
id                                                                
1000044                               Working Title Films  1000044
1000165                               Working Title Films  1000165
1000263                               Working Title Films  1000263
1000514                                            Fabula  1000514
1000547                               Working Title Films  1000547
...                                                   ...      ...
1852028                                              ARTE  1852028
1859604                                              ARTE  1859604
1863229                                        Star Media  1863229
1888903  Deutsche Film- und Fernsehakademie Berlin (DFFB)  1888903
1934998                           Ministerstvo kultury ČR  1934998

[212 rows x 2 columns]

it is possible to see that a single studio can appear multiple time in the dataframe for each movie. This could be it because a studio could have worked in different areas of the movie filming session but the dataframe does not show all the different area so the duplicates will be removed.

In [72]:
studios_df = studios_df[~studios_df['studio'].duplicated()].copy()

removing the helper column


In [73]:
studios_df.drop(['index'], axis=1)

studio
id                                         
1000001             LuckyChap Entertainment
1000001                        Heyday Films
1000001                      NB/GG Pictures
1000001                              Mattel
1000001               Warner Bros. Pictures
...                                     ...
1941514                  TCGT Entertainment
1941522  Trailblazing Films & Entertainment
1941534                         Lo Vi Films
1941596                       坏小子（北京）传媒有限公司
1941596                    亚太国影（重庆）文化传媒有限公司

[160881 rows x 1 columns]

In [74]:
themes_df

theme
id                                                        
1000001                   Humanity and the world around us
1000001                             Crude humor and satire
1000001                        Moving relationship stories
1000001     Emotional and captivating fantasy storytelling
1000001  Surreal and thought-provoking visions of life ...
...                                                    ...
1835643                         Noir and dark crime dramas
1835643        Intriguing and suspenseful murder mysteries
1849827                                 Faith and religion
1849827                       Faith and spiritual journeys
1849827              Religious faith, sin, and forgiveness

[125641 rows x 1 columns]

In [75]:
themes_df.loc[themes_df['theme'].isna()]

Empty DataFrame
Columns: [theme]
Index: []

In [76]:
themes_df['index'] = themes_df.index
themes_df.loc[themes_df.duplicated(subset=['index','theme'])]

Empty DataFrame
Columns: [theme, index]
Index: []

In [77]:
rotten_tomatoes_df

rotten_tomatoes_link  \
review_id                                                       
m/0814255_Andrew L. Urban_2010-02-06                m/0814255   
m/0814255_Louise Keller_2010-02-06                  m/0814255   
m/0814255_Unknown_2010-02-09                        m/0814255   
m/0814255_Ben McEachen_2010-02-09                   m/0814255   
m/0814255_Ethan Alter_2010-02-10                    m/0814255   
...                                                       ...   
m/zulu_dawn_Chuck O'Leary_2005-11-02              m/zulu_dawn   
m/zulu_dawn_Ken Hanke_2007-03-07                  m/zulu_dawn   
m/zulu_dawn_Dennis Schwartz_2010-09-16            m/zulu_dawn   
m/zulu_dawn_Christopher Lloyd_2011-02-28          m/zulu_dawn   
m/zulu_dawn_Brent McKnight_2020-07-09             m/zulu_dawn   

                                                                                movie_title  \
review_id                                                                                     
m/0814255_Andrew L. Urban_2010-02-06      Percy Jackson & the Olympians: The Lightning T...   
m/0814255_Louise Keller_2010-02-06        Percy Jackson & the Olympians: The Lightning T...   
m/0814255_Unknown_2010-02-09              Percy Jackson & the Olympians: The Lightning T...   
m/0814255_Ben McEachen_2010-02-09         Percy Jackson & the Olympians: The Lightning T...   
m/0814255_Ethan Alter_2010-02-10          Percy Jackson & the Olympians: The Lightning T...   
...                                                                                     ...   
m/zulu_dawn_Chuck O'Leary_2005-11-02                                              Zulu Dawn   
m/zulu_dawn_Ken Hanke_2007-03-07                                                  Zulu Dawn   
m/zulu_dawn_Dennis Schwartz_2010-09-16                                            Zulu Dawn   
m/zulu_dawn_Christopher Lloyd_2011-02-28                                          Zulu Dawn   
m/zulu_dawn_Brent McKnight_2020-07-09                                             Zulu Dawn   

                                                critic_name  top_critic  \
review_id                                                                 
m/0814255_Andrew L. Urban_2010-02-06        Andrew L. Urban       False   
m/0814255_Louise Keller_2010-02-06            Louise Keller       False   
m/0814255_Unknown_2010-02-09                            NaN       False   
m/0814255_Ben McEachen_2010-02-09              Ben McEachen       False   
m/0814255_Ethan Alter_2010-02-10                Ethan Alter        True   
...                                                     ...         ...   
m/zulu_dawn_Chuck O'Leary_2005-11-02          Chuck O'Leary       False   
m/zulu_dawn_Ken Hanke_2007-03-07                  Ken Hanke       False   
m/zulu_dawn_Dennis Schwartz_2010-09-16      Dennis Schwartz       False   
m/zulu_dawn_Christopher Lloyd_2011-02-28  Christopher Lloyd       False   
m/zulu_dawn_Brent McKnight_2020-07-09        Brent McKnight       False   

                                                           publisher_name  \
review_id                                                                   
m/0814255_Andrew L. Urban_2010-02-06                       Urban Cinefile   
m/0814255_Louise Keller_2010-02-06                         Urban Cinefile   
m/0814255_Unknown_2010-02-09                          FILMINK (Australia)   
m/0814255_Ben McEachen_2010-02-09                 Sunday Mail (Australia)   
m/0814255_Ethan Alter_2010-02-10                       Hollywood Reporter   
...                                                                   ...   
m/zulu_dawn_Chuck O'Leary_2005-11-02                     Fantastica Daily   
m/zulu_dawn_Ken Hanke_2007-03-07          Mountain Xpress (Asheville, NC)   
m/zulu_dawn_Dennis Schwartz_2010-09-16      Dennis Schwartz Movie Reviews   
m/zulu_dawn_Christopher Lloyd_2011-02-28          Sarasota Herald-Tribune   
m/zulu_dawn_Brent McKnight_2020-07-09                The La

In [78]:
rotten_tomatoes_df.dtypes

rotten_tomatoes_link    object
movie_title             object
critic_name             object
top_critic                bool
publisher_name          object
review_type             object
review_score            object
review_date             object
review_content          object
dtype: object

In [79]:
rotten_tomatoes_df['rotten_tomatoes_link'] = rotten_tomatoes_df['rotten_tomatoes_link'].astype(pd.StringDtype())
rotten_tomatoes_df['movie_title'] = rotten_tomatoes_df['movie_title'].astype(pd.StringDtype())
rotten_tomatoes_df['critic_name'] = rotten_tomatoes_df['critic_name'].astype(pd.StringDtype())
rotten_tomatoes_df['publisher_name'] = rotten_tomatoes_df['publisher_name'].astype(pd.StringDtype())
rotten_tomatoes_df['review_type'] = rotten_tomatoes_df['review_type'].astype(pd.StringDtype())
rotten_tomatoes_df['review_score'] = rotten_tomatoes_df['review_score'].astype(pd.StringDtype())
rotten_tomatoes_df['review_date'] = pd.to_datetime( rotten_tomatoes_df['review_date'])
rotten_tomatoes_df['review_content'] = rotten_tomatoes_df['review_content'].astype(pd.StringDtype())

In [80]:
rotten_tomatoes_df.dtypes

rotten_tomatoes_link    string[python]
movie_title             string[python]
critic_name             string[python]
top_critic                        bool
publisher_name          string[python]
review_type             string[python]
review_score            string[python]
review_date             datetime64[ns]
review_content          string[python]
dtype: object

In [81]:
rotten_tomatoes_df.loc[rotten_tomatoes_df[['critic_name','publisher_name']].isna().all(axis=1)]

Empty DataFrame
Columns: [rotten_tomatoes_link, movie_title, critic_name, top_critic, publisher_name, review_type, review_score, review_date, review_content]
Index: []

In [82]:
rotten_tomatoes_df.loc[rotten_tomatoes_df[['review_type','review_score']].isna().all(axis=1)]

Empty DataFrame
Columns: [rotten_tomatoes_link, movie_title, critic_name, top_critic, publisher_name, review_type, review_score, review_date, review_content]
Index: []

meaningfull duplicates

In [83]:
rotten_tomatoes_df.loc[rotten_tomatoes_df.duplicated(subset=['rotten_tomatoes_link','critic_name','publisher_name','review_type','review_date','review_score', 'review_content'])]

rotten_tomatoes_link  \
review_id                                                                                               
m/1069696-screamers_Dave White_1996-01-26                                         m/1069696-screamers   
m/1069707-othello_Fred Topel_2003-11-25                                             m/1069707-othello   
m/1087935-buena_vista_social_club_Unknown_2002-...                  m/1087935-buena_vista_social_club   
m/1087935-buena_vista_social_club_Unknown_2005-...                  m/1087935-buena_vista_social_club   
m/1105979-brothers_Unknown_2002-12-08                                              m/1105979-brothers   
...                                                                                               ...   
m/super_duper_alice_cooper_Jeff Baker_2014-10-10                           m/super_duper_alice_cooper   
m/super_duper_alice_cooper_Pat Padua_2018-08-31                            m/super_duper_alice_cooper   
m/the_fog_of_war_eleven_lessons_from_the_life_o...  m/the_fog_of_war_eleven_lessons_from_the_life_...   
m/the_girl_with_the_dragon_tattoo_2009_Unknown_...             m/the_girl_with_the_dragon_tattoo_2009   
m/together_2001_Unknown_2002-12-08                                                    m/together_2001   

                                                                                          movie_title  \
review_id                                                                                               
m/1069696-screamers_Dave White_1996-01-26                                                   Screamers   
m/1069707-othello_Fred Topel_2003-11-25                                                       Othello   
m/1087935-buena_vista_social_club_Unknown_2002-...                            Buena Vista Social Club   
m/1087935-buena_vista_social_club_Unknown_2005-...                            Buena Vista Social Club   
m/1105979-brothers_Unknown_2002-12-08                                                    The Brothers   
...                                                                                               ...   
m/super_duper_alice_cooper_Jeff Baker_2014-10-10                             Super Duper Alice Cooper   
m/super_duper_alice_cooper_Pat Padua_2018-08-31                              Super Duper Alice Cooper   
m/the_fog_of_war_eleven_lessons_from_the_life_o...  The Fog of War: Eleven Lessons from the Life o...   
m/the_girl_with_the_dragon_tattoo_2009_Unknown_...                    The Girl with the Dragon Tattoo   
m/together_2001_Unknown_2002-12-08                                                           Together   

                                                   critic_name  top_critic  \
review_id                                                                    
m/1069696-screamers_Dave White_1996-01-26           Dave White       False   
m/1069707-othello_Fred Topel_2003-11-25             Fred Topel       False   
m/1087935-buena_vista_social_club_Unknown_2002-...        <NA>       False   
m/1087935-buena_vista_social_club_Unknown_2005-...        <NA>       False   
m/1105979-brothers_Unknown_2002-12-08                     <NA>       False   
...                                                        ...         ...   
m/super_duper_alice_cooper_Jeff Baker_2014-10-10    Jeff Baker       False   
m/super_duper_alice_cooper_Pat Padua_2018-08-31      Pat Padua       False   
m/the_fog_of_war_eleven_lessons_from_the_life_o...        <NA>       False   
m/the_girl_with_the_dragon_tattoo_2009_Unknown_...        <NA>       False   
m/together_2001_Unknown_2002-12-08                        <NA>       False   

                                                      publisher_name  \
review_id                                                              
m/1069696-screamers_Dave White_1996-01-26                 Movies.com   
m/1069707-othello_Fred Topel_2003-11-25                    About.com   
m/1087935-buena_vista_social_club_Unknown_2002

In [84]:
reviews_df = rotten_tomatoes_df[~rotten_tomatoes_df.duplicated(subset=['rotten_tomatoes_link','critic_name','publisher_name','review_type','review_date','review_score', 'review_content'])].copy()

In [85]:
oscar_awards_df

year_film  year_ceremony  \
oscar_id                                                                       
1927_ACTOR_Richard Barthelmess                           1927           1928   
1927_ACTOR_Emil Jannings                                 1927           1928   
1927_ACTRESS_Louise Dresser                              1927           1928   
1927_ACTRESS_Janet Gaynor                                1927           1928   
1927_ACTRESS_Gloria Swanson                              1927           1928   
...                                                       ...            ...   
2023_WRITING (Original Screenplay)_Written by C...       2023           2024   
NaN                                                      2023           2024   
2023_HONORARY AWARD_To Angela Bassett, who has ...       2023           2024   
2023_HONORARY AWARD_To Mel Brooks, for his come...       2023           2024   
2023_HONORARY AWARD_To Carol Littleton, whose c...       2023           2024   

                                                    ceremony  \
oscar_id                                                       
1927_ACTOR_Richard Barthelmess                             1   
1927_ACTOR_Emil Jannings                                   1   
1927_ACTRESS_Louise Dresser                                1   
1927_ACTRESS_Janet Gaynor                                  1   
1927_ACTRESS_Gloria Swanson                                1   
...                                                      ...   
2023_WRITING (Original Screenplay)_Written by C...        96   
NaN                                                       96   
2023_HONORARY AWARD_To Angela Bassett, who has ...        96   
2023_HONORARY AWARD_To Mel Brooks, for his come...        96   
2023_HONORARY AWARD_To Carol Littleton, whose c...        96   

                                                                            category  \
oscar_id                                                                               
1927_ACTOR_Richard Barthelmess                                                 ACTOR   
1927_ACTOR_Emil Jannings                                                       ACTOR   
1927_ACTRESS_Louise Dresser                                                  ACTRESS   
1927_ACTRESS_Janet Gaynor                                                    ACTRESS   
1927_ACTRESS_Gloria Swanson                                                  ACTRESS   
...                                                                              ...   
2023_WRITING (Original Screenplay)_Written by C...     WRITING (Original Screenplay)   
NaN                                                 JEAN HERSHOLT HUMANITARIAN AWARD   
2023_HONORARY AWARD_To Angela Bassett, who has ...                    HONORARY AWARD   
2023_HONORARY AWARD_To Mel Brooks, for his come...                    HONORARY AWARD   
2023_HONORARY AWARD_To Carol Littleton, whose c...                    HONORARY AWARD   

                                                                                                 name  \
oscar_id                                                                                                
1927_ACTOR_Richard Barthelmess                                                    Richard Barthelmess   
1927_ACTOR_Emil Jannings                                                                Emil Jannings   
1927_ACTRESS_Louise Dresser                                                            Louise Dresser   
1927_ACTRESS_Janet Gaynor                                                                Janet Gaynor   
1927_ACTRESS_Gloria Swanson                                                            Gloria Swanson   
...                                                                                               ...   
2023_WRITING (Original Screenplay)_Written by C...                             Written by Celine Song   
NaN                                                                                     

In [86]:
from IPython.display import display

# Visualizza i tipi delle colonne in modo tabellare
display(oscar_awards_df.dtypes)

dtypes_df = pd.DataFrame(oscar_awards_df.dtypes, columns=['Data Type'])
display(dtypes_df)

year_film         int64
year_ceremony     int64
ceremony          int64
category         object
name             object
film             object
winner             bool
dtype: object

Data Type
year_film         int64
year_ceremony     int64
ceremony          int64
category         object
name             object
film             object
winner             bool

In [87]:
oscar_awards_df['category'] = oscar_awards_df['category'].astype(pd.StringDtype())
oscar_awards_df['name'] = oscar_awards_df['name'].astype(pd.StringDtype())
oscar_awards_df['film'] = oscar_awards_df['film'].astype(pd.StringDtype())

In [88]:
# Visualizza i tipi delle colonne in modo tabellare
display(oscar_awards_df.dtypes)

dtypes_df = pd.DataFrame(oscar_awards_df.dtypes, columns=['Data Type'])
display(dtypes_df)

year_film                 int64
year_ceremony             int64
ceremony                  int64
category         string[python]
name             string[python]
film             string[python]
winner                     bool
dtype: object

Data Type
year_film               int64
year_ceremony           int64
ceremony                int64
category       string[python]
name           string[python]
film           string[python]
winner                   bool

In [89]:
oscar_awards_df.loc[oscar_awards_df.isna().any(axis=1)]

year_film  year_ceremony  \
oscar_id                                                                       
1927_ENGINEERING EFFECTS_Ralph Hammeras                  1927           1928   
1927_ENGINEERING EFFECTS_Nugent Slaughter                1927           1928   
1927_WRITING (Title Writing)_Joseph Farnham              1927           1928   
1927_WRITING (Title Writing)_George Marion, Jr.          1927           1928   
1927_SPECIAL AWARD_ Warner Bros.                         1927           1928   
...                                                       ...            ...   
2022_GORDON E. SAWYER AWARD_Iain Neil                    2022           2023   
NaN                                                      2023           2024   
2023_HONORARY AWARD_To Angela Bassett, who has ...       2023           2024   
2023_HONORARY AWARD_To Mel Brooks, for his come...       2023           2024   
2023_HONORARY AWARD_To Carol Littleton, whose c...       2023           2024   

                                                    ceremony  \
oscar_id                                                       
1927_ENGINEERING EFFECTS_Ralph Hammeras                    1   
1927_ENGINEERING EFFECTS_Nugent Slaughter                  1   
1927_WRITING (Title Writing)_Joseph Farnham                1   
1927_WRITING (Title Writing)_George Marion, Jr.            1   
1927_SPECIAL AWARD_ Warner Bros.                           1   
...                                                      ...   
2022_GORDON E. SAWYER AWARD_Iain Neil                     95   
NaN                                                       96   
2023_HONORARY AWARD_To Angela Bassett, who has ...        96   
2023_HONORARY AWARD_To Mel Brooks, for his come...        96   
2023_HONORARY AWARD_To Carol Littleton, whose c...        96   

                                                                            category  \
oscar_id                                                                               
1927_ENGINEERING EFFECTS_Ralph Hammeras                          ENGINEERING EFFECTS   
1927_ENGINEERING EFFECTS_Nugent Slaughter                        ENGINEERING EFFECTS   
1927_WRITING (Title Writing)_Joseph Farnham                  WRITING (Title Writing)   
1927_WRITING (Title Writing)_George Marion, Jr.              WRITING (Title Writing)   
1927_SPECIAL AWARD_ Warner Bros.                                       SPECIAL AWARD   
...                                                                              ...   
2022_GORDON E. SAWYER AWARD_Iain Neil                         GORDON E. SAWYER AWARD   
NaN                                                 JEAN HERSHOLT HUMANITARIAN AWARD   
2023_HONORARY AWARD_To Angela Bassett, who has ...                    HONORARY AWARD   
2023_HONORARY AWARD_To Mel Brooks, for his come...                    HONORARY AWARD   
2023_HONORARY AWARD_To Carol Littleton, whose c...                    HONORARY AWARD   

                                                                                                 name  \
oscar_id                                                                                                
1927_ENGINEERING EFFECTS_Ralph Hammeras                                                Ralph Hammeras   
1927_ENGINEERING EFFECTS_Nugent Slaughter                                            Nugent Slaughter   
1927_WRITING (Title Writing)_Joseph Farnham                                            Joseph Farnham   
1927_WRITING (Title Writing)_George Marion, Jr.                                    George Marion, Jr.   
1927_SPECIAL AWARD_ Warner Bros.                                                         Warner Bros.   
...                                                                                               ...   
2022_GORDON E. SAWYER AWARD_Iain Neil                                                       Iain Neil   
NaN                                                                                     

In [91]:
oscar_awards_df.loc[oscar_awards_df.duplicated(subset=['category','name','film']) & ~oscar_awards_df['film'].isna()]

year_film  year_ceremony  \
oscar_id                                                                       
1983_MUSIC (Original Song)_Music by Michel Legr...       1983           1984   
1989_MUSIC (Original Song)_Music by Alan Menken...       1989           1990   
1991_MUSIC (Original Song)_Music by Alan Menken...       1991           1992   
1991_MUSIC (Original Song)_Music by Alan Menken...       1991           1992   
1994_MUSIC (Original Song)_Music by Elton John;...       1994           1995   
1994_MUSIC (Original Song)_Music by Elton John;...       1994           1995   
2007_MUSIC (Original Song)_Music by Alan Menken...       2007           2008   
2007_MUSIC (Original Song)_Music by Alan Menken...       2007           2008   
2009_MUSIC (Original Song)_Music and Lyric by R...       2009           2010   
2016_MUSIC (Original Song)_Music by Justin Hurw...       2016           2017   

                                                    ceremony  \
oscar_id                                                       
1983_MUSIC (Original Song)_Music by Michel Legr...        56   
1989_MUSIC (Original Song)_Music by Alan Menken...        62   
1991_MUSIC (Original Song)_Music by Alan Menken...        64   
1991_MUSIC (Original Song)_Music by Alan Menken...        64   
1994_MUSIC (Original Song)_Music by Elton John;...        67   
1994_MUSIC (Original Song)_Music by Elton John;...        67   
2007_MUSIC (Original Song)_Music by Alan Menken...        80   
2007_MUSIC (Original Song)_Music by Alan Menken...        80   
2009_MUSIC (Original Song)_Music and Lyric by R...        82   
2016_MUSIC (Original Song)_Music by Justin Hurw...        89   

                                                                 category  \
oscar_id                                                                    
1983_MUSIC (Original Song)_Music by Michel Legr...  MUSIC (Original Song)   
1989_MUSIC (Original Song)_Music by Alan Menken...  MUSIC (Original Song)   
1991_MUSIC (Original Song)_Music by Alan Menken...  MUSIC (Original Song)   
1991_MUSIC (Original Song)_Music by Alan Menken...  MUSIC (Original Song)   
1994_MUSIC (Original Song)_Music by Elton John;...  MUSIC (Original Song)   
1994_MUSIC (Original Song)_Music by Elton John;...  MUSIC (Original Song)   
2007_MUSIC (Original Song)_Music by Alan Menken...  MUSIC (Original Song)   
2007_MUSIC (Original Song)_Music by Alan Menken...  MUSIC (Original Song)   
2009_MUSIC (Original Song)_Music and Lyric by R...  MUSIC (Original Song)   
2016_MUSIC (Original Song)_Music by Justin Hurw...  MUSIC (Original Song)   

                                                                                                 name  \
oscar_id                                                                                                
1983_MUSIC (Original Song)_Music by Michel Legr...  Music by Michel Legrand; Lyric by Alan Bergman...   
1989_MUSIC (Original Song)_Music by Alan Menken...       Music by Alan Menken; Lyric by Howard Ashman   
1991_MUSIC (Original Song)_Music by Alan Menken...       Music by Alan Menken; Lyric by Howard Ashman   
1991_MUSIC (Original Song)_Music by Alan Menken...       Music by Alan Menken; Lyric by Howard Ashman   
1994_MUSIC (Original Song)_Music by Elton John;...             Music by Elton John; Lyric by Tim Rice   
1994_MUSIC (Original Song)_Music by Elton John;...             Music by Elton John; Lyric by Tim Rice   
2007_MUSIC (Original Song)_Music by Alan Menken...    Music by Alan Menken; Lyric by Stephen Schwartz   
2007_MUSIC (Original Song)_Music by Alan Menken...    Music by Alan Menken; Lyric by Stephen Schwartz   
2009_MUSIC (Original Song)_Music and Lyric by R...                    Music and Lyric by Randy Newman   
2016_MUSIC (Original Song)_Music by Justin Hurw...  Music by Justin Hurwitz; Lyric by Benj Pasek a...   

                                                                         film  \
oscar_id                                               

In [92]:
oscar_awards_df = oscar_awards_df.loc[~oscar_awards_df.duplicated(subset=['category','name','film']) & ~oscar_awards_df['film'].isna()]

oscar_awards_df

year_film  year_ceremony  \
oscar_id                                                                       
1927_ACTOR_Richard Barthelmess                           1927           1928   
1927_ACTOR_Emil Jannings                                 1927           1928   
1927_ACTRESS_Louise Dresser                              1927           1928   
1927_ACTRESS_Janet Gaynor                                1927           1928   
1927_ACTRESS_Gloria Swanson                              1927           1928   
...                                                       ...            ...   
2023_WRITING (Original Screenplay)_Screenplay -...       2023           2024   
2023_WRITING (Original Screenplay)_Written by D...       2023           2024   
2023_WRITING (Original Screenplay)_Written by B...       2023           2024   
2023_WRITING (Original Screenplay)_Screenplay b...       2023           2024   
2023_WRITING (Original Screenplay)_Written by C...       2023           2024   

                                                    ceremony  \
oscar_id                                                       
1927_ACTOR_Richard Barthelmess                             1   
1927_ACTOR_Emil Jannings                                   1   
1927_ACTRESS_Louise Dresser                                1   
1927_ACTRESS_Janet Gaynor                                  1   
1927_ACTRESS_Gloria Swanson                                1   
...                                                      ...   
2023_WRITING (Original Screenplay)_Screenplay -...        96   
2023_WRITING (Original Screenplay)_Written by D...        96   
2023_WRITING (Original Screenplay)_Written by B...        96   
2023_WRITING (Original Screenplay)_Screenplay b...        96   
2023_WRITING (Original Screenplay)_Written by C...        96   

                                                                         category  \
oscar_id                                                                            
1927_ACTOR_Richard Barthelmess                                              ACTOR   
1927_ACTOR_Emil Jannings                                                    ACTOR   
1927_ACTRESS_Louise Dresser                                               ACTRESS   
1927_ACTRESS_Janet Gaynor                                                 ACTRESS   
1927_ACTRESS_Gloria Swanson                                               ACTRESS   
...                                                                           ...   
2023_WRITING (Original Screenplay)_Screenplay -...  WRITING (Original Screenplay)   
2023_WRITING (Original Screenplay)_Written by D...  WRITING (Original Screenplay)   
2023_WRITING (Original Screenplay)_Written by B...  WRITING (Original Screenplay)   
2023_WRITING (Original Screenplay)_Screenplay b...  WRITING (Original Screenplay)   
2023_WRITING (Original Screenplay)_Written by C...  WRITING (Original Screenplay)   

                                                                                                 name  \
oscar_id                                                                                                
1927_ACTOR_Richard Barthelmess                                                    Richard Barthelmess   
1927_ACTOR_Emil Jannings                                                                Emil Jannings   
1927_ACTRESS_Louise Dresser                                                            Louise Dresser   
1927_ACTRESS_Janet Gaynor                                                                Janet Gaynor   
1927_ACTRESS_Gloria Swanson                                                            Gloria Swanson   
...                                                                                               ...   
2023_WRITING (Original Screenplay)_Screenplay -...       Screenplay - Justine Triet and Arthur Harari   
2023_WRITING (Original Screenplay)_Written by D...                         Written by David Hemingson   
2023_WRITING (Original

In [93]:
import numpy as np

oscar_awards_df = oscar_awards_df.replace({np.nan: None})

In [90]:
dataloader._save_data()

In [81]:

print("Movie columns:", movies_df.columns)
print("Actors columns:", actors_df.columns)
print("Countries columns:", countries_df.columns)
print("Crew columns:", crew_df.columns)
print("Genres columns:", genres_df.columns)
print("Languages columns:", languages_df.columns)
print("Posters columns:", posters_df.columns)
print("Release columns:", releases_df.columns)
print("Studios columns:", studios_df.columns)
print("Themes columns:", themes_df.columns)
print("Oscar columns:", oscar_awards_df.columns)
print("Rotten columns:", rotten_tomatoes_df.columns)

Movie columns: Index(['name', 'date', 'tagline', 'description', 'minute', 'rating',
       'movie_id'],
      dtype='object')
Actors columns: Index(['name', 'role'], dtype='object')
Countries columns: Index(['country'], dtype='object')
Crew columns: Index(['role', 'name'], dtype='object')
Genres columns: Index(['genre'], dtype='object')
Languages columns: Index(['type', 'language'], dtype='object')
Posters columns: Index(['link'], dtype='object')
Release columns: Index(['country', 'date', 'type', 'rating', 'index'], dtype='object')
Studios columns: Index(['studio'], dtype='object')
Themes columns: Index(['theme'], dtype='object')
Oscar columns: Index(['year_film', 'year_ceremony', 'ceremony', 'category', 'name', 'film',
       'winner'],
      dtype='object')
Rotten columns: Index(['rotten_tomatoes_link', 'movie_title', 'critic_name', 'top_critic',
       'publisher_name', 'review_type', 'review_score', 'review_date',
       'review_content'],
      dtype='object')


In [86]:
from os import mkdir

# Funzione per creare un mapping unico con ID
def create_mapping_table(df, column_name, id_column_name):
    unique_values = df[column_name].drop_duplicates().reset_index(drop=True)
    mapping_table = pd.DataFrame({id_column_name: range(1, len(unique_values) + 1), column_name: unique_values})
    return mapping_table

# Creazione di un ID per i film (già presente in movies_df)
movies_df['movie_id'] = range(1, len(movies_df) + 1)

# Normalizzazione delle altre tabelle

# Attori
actors_mapping = create_mapping_table(actors_df, 'name', 'actor_id')
movie_actors_df = actors_df.merge(actors_mapping, on='name', how='inner')
movie_actors_df = movie_actors_df.merge(movies_df[['movie_id', 'name']], on='name', how='inner')[['movie_id', 'actor_id', 'role']]

# Paesi
countries_mapping = create_mapping_table(countries_df, 'country', 'country_id')
movie_countries_df = releases_df.merge(countries_mapping, on='country', how='inner')
movie_countries_df = movie_countries_df.merge(movies_df[['movie_id', 'name']], left_on='country', right_on='name', how='inner')[['movie_id', 'country_id']]

# Crew (ruoli e nomi associati ai film)
crew_mapping = create_mapping_table(crew_df, 'name', 'crew_id')
movie_crew_df = crew_df.merge(crew_mapping, on='name', how='inner')
movie_crew_df = movie_crew_df.merge(movies_df[['movie_id', 'name']], on='name', how='inner')[['movie_id', 'crew_id', 'role']]

# Generi
genres_mapping = create_mapping_table(genres_df, 'genre', 'genre_id')
movie_genres_df = genres_df.merge(genres_mapping, on='genre', how='inner')
movie_genres_df = movie_genres_df.merge(movies_df[['movie_id', 'name']], left_on='genre', right_on='name', how='inner')[['movie_id', 'genre_id']]

# Lingue
languages_mapping = create_mapping_table(languages_df, 'language', 'language_id')
movie_languages_df = languages_df.merge(languages_mapping, on='language', how='inner')
movie_languages_df = movie_languages_df.merge(movies_df[['movie_id', 'name']], left_on='language', right_on='name', how='inner')[['movie_id', 'language_id', 'type']]

# Temi
themes_mapping = create_mapping_table(themes_df, 'theme', 'theme_id')
movie_themes_df = themes_df.merge(themes_mapping, on='theme', how='inner')
movie_themes_df = movie_themes_df.merge(movies_df[['movie_id', 'name']], left_on='theme', right_on='name', how='inner')[['movie_id', 'theme_id']]

# Studios
studios_mapping = create_mapping_table(studios_df, 'studio', 'studio_id')
movie_studios_df = studios_df.merge(studios_mapping, on='studio', how='inner')
movie_studios_df = movie_studios_df.merge(movies_df[['movie_id', 'name']], left_on='studio', right_on='name', how='inner')[['movie_id', 'studio_id']]

# Oscar Awards
movie_oscars_df = oscar_awards_df.merge(
    movies_df[['movie_id', 'name']],
    left_on='film',
    right_on='name',
    how='inner'
)

# Rinomina colonne e seleziona quelle richieste
movie_oscars_df = movie_oscars_df.rename(columns={'name_x': 'person_name', 'name_y': 'film_name'})
movie_oscars_df = movie_oscars_df[['movie_id', 'year_film', 'year_ceremony', 'ceremony', 'category', 'person_name', 'winner']]

# Rotten Tomatoes
movie_rotten_df = rotten_tomatoes_df.merge(
    movies_df[['movie_id', 'name']],
    left_on='movie_title',
    right_on='name',
    how='inner'
)

# Rinomina colonne e seleziona quelle richieste
movie_rotten_df = movie_rotten_df.rename(columns={'name': 'film_name'})
movie_rotten_df = movie_rotten_df[['movie_id', 'critic_name', 'top_critic', 'publisher_name', 'review_type', 'review_score', 'review_date', 'review_content']]

# Normalizzazione completata

# Creazione directory di output
output_path = "./normalized_tables/"
mkdir(output_path)

# Esportazione delle tabelle normalizzate
movies_df.to_csv(f"{output_path}movies.csv", index=False)
actors_mapping.to_csv(f"{output_path}actors.csv", index=False)
movie_actors_df.to_csv(f"{output_path}actors_movies.csv", index=False)
countries_mapping.to_csv(f"{output_path}countries.csv", index=False)
movie_countries_df.to_csv(f"{output_path}countries_movies.csv", index=False)
crew_mapping.to_csv(f"{output_path}crew.csv", index=False)
movie_crew_df.to_csv(f"{output_path}crew_movies.csv", index=False)
genres_mapping.to_csv(f"{output_path}genres.csv", index=False)
movie_genres_df.to_csv(f"{output_path}genres_movies.csv", index=False)
languages_mapping.to_csv(f"{output_path}languages.csv", index=False)
movie_languages_df.to_csv(f"{output_path}languages_movies.csv", index=False)
themes_mapping.to_csv(f"{output_path}themes.csv", index=False)
movie_themes_df.to_csv(f"{output_path}themes_movies.csv", index=False)
studios_mapping.to_csv(f"{output_path}studios.csv", index=False)
movie_studios_df.to_csv(f"{output_path}studios_movies.csv", index=False)
movie_oscars_df.to_csv(f"{output_path}oscars_movies.csv", index=False)
movie_rotten_df.to_csv(f"{output_path}rotten_movies.csv", index=False)

In [ ]:
#caricare dati nelle tabelle