In [435]:
from IPython.display import Image, display
import DataLoader as dl
import pandas as pd

dataloader = dl.DataLoader()

movies_df = dataloader.movies_df
actors_df = dataloader.actors_df
countries_df = dataloader.countries_df
crew_df = dataloader.crew_df
genres_df = dataloader.genres_df
languages_df = dataloader.languages_df
posters_df = dataloader.posters_df
releases_df = dataloader.releases_df
studios_df = dataloader.studios_df
themes_df = dataloader.themes_df

movies_df

name    date  \
id                                                   
1000001                             Barbie  2023.0   
1000002                           Parasite  2019.0   
1000003  Everything Everywhere All at Once  2022.0   
1000004                         Fight Club  1999.0   
1000005                         La La Land  2016.0   
...                                    ...     ...   
1941593                                 神笛     NaN   
1941594                      蟲極道蜜団子抗争編 壱ノ巻     NaN   
1941595                      蟲極道蜜団子抗争編 弐ノ巻     NaN   
1941596                                 重生     NaN   
1941597                             青ひげ公の城     NaN   

                                                  tagline  \
id                                                          
1000001                  She's everything. He's just Ken.   
1000002                       Act like you own the place.   
1000003  The universe is so much bigger than you realize.   
1000004                           Mischief. Mayhem. Soap.   
1000005                    Here's to the fools who dream.   
...                                                   ...   
1941593                                               NaN   
1941594                                               NaN   
1941595                                               NaN   
1941596                                               NaN   
1941597                                               NaN   

                                               description  minute  rating  
id                                                                          
1000001  Barbie and Ken are having the time of their li...   114.0    3.86  
1000002  All unemployed, Ki-taek's family takes peculia...   133.0    4.56  
1000003  An aging Chinese immigrant is swept up in an i...   140.0    4.30  
1000004  A ticking-time-bomb insomniac and a slippery s...   139.0    4.27  
1000005  Mia, an aspiring actress, serves lattes to mov...   129.0    4.09  
...                                                    ...     ...     ...  
1941593                                                NaN     NaN     NaN  
1941594  Shinjuku forest at night. In the sap taverns o...    30.0     NaN  
1941595  The city that never sleeps, where insects gath...    30.0     NaN  
1941596  In a world where order has broken down, darkne...     NaN     NaN  
1941597                                                NaN   130.0     NaN  

[941597 rows x 6 columns]

In [436]:
print("Movie columns:" , movies_df.columns)
print("Actors columns:" , actors_df.columns)
print("Countries columns:" , countries_df.columns)
print("Crew columns:" , crew_df.columns)
print("Genres columns:" , genres_df.columns)
print("Languages columns:" , languages_df.columns)
print("Posters columns:" , posters_df.columns)
print("Release columns:" , releases_df.columns)
print("Studios columns:" , studios_df.columns)
print("Themes columns:" , themes_df.columns)

Movie columns: Index(['name', 'date', 'tagline', 'description', 'minute', 'rating'], dtype='object')
Actors columns: Index(['name', 'role'], dtype='object')
Countries columns: Index(['country'], dtype='object')
Crew columns: Index(['role', 'name'], dtype='object')
Genres columns: Index(['genre'], dtype='object')
Languages columns: Index(['type', 'language'], dtype='object')
Posters columns: Index(['link'], dtype='object')
Release columns: Index(['country', 'date', 'type', 'rating'], dtype='object')
Studios columns: Index(['studio'], dtype='object')
Themes columns: Index(['theme'], dtype='object')


# Data Cleaning
## Removing or replacing all the data that are not compliant with the dataset
### Dataset types:


fetch and cast the data to their correct type

In [437]:
movies_df.dtypes

name            object
date           float64
tagline         object
description     object
minute         float64
rating         float64
dtype: object

In [438]:
movies_df['name'] = movies_df['name'].astype(pd.StringDtype())
movies_df['tagline'] = movies_df['tagline'].astype(pd.StringDtype())
movies_df['description'] = movies_df['description'].astype(pd.StringDtype())
movies_df['date'] = movies_df['date'].astype('Int64')

In [439]:
movies_df.dtypes

name           string[python]
date                    Int64
tagline        string[python]
description    string[python]
minute                float64
rating                float64
dtype: object

In [440]:
actors_df.dtypes

name    object
role    object
dtype: object

In [441]:
actors_df['name'] = actors_df['name'].astype(pd.StringDtype())
actors_df['role'] = actors_df['role'].astype(pd.StringDtype())

In [442]:
countries_df.dtypes

country    object
dtype: object

In [443]:
countries_df['country'] = countries_df['country'].astype(pd.StringDtype())

In [444]:
crew_df.dtypes

role    object
name    object
dtype: object

In [445]:
crew_df['role'] = crew_df['role'].astype(pd.StringDtype())
crew_df['name'] = crew_df['name'].astype(pd.StringDtype())

In [446]:
genres_df.dtypes

genre    object
dtype: object

In [447]:
genres_df['genre'] = genres_df['genre'].astype(pd.StringDtype())

In [448]:
languages_df.dtypes

type        object
language    object
dtype: object

In [449]:
languages_df['type'] = languages_df['type'].astype(pd.StringDtype())
languages_df['language'] = languages_df['language'].astype(pd.StringDtype())

In [450]:
posters_df.dtypes

link    object
dtype: object

In [451]:
posters_df['link'] = posters_df['link'].astype(pd.StringDtype())

In [452]:
releases_df.dtypes

country    object
date       object
type       object
rating     object
dtype: object

In [453]:
releases_df['country'] = releases_df['country'].astype(pd.StringDtype())
releases_df['date'] = releases_df['date'].astype(pd.StringDtype()) #todo: change to date type
releases_df['type'] = releases_df['type'].astype(pd.StringDtype())
releases_df['rating'] = releases_df['rating'].astype(pd.StringDtype())

In [454]:
studios_df.dtypes

studio    object
dtype: object

In [455]:
studios_df['studio'] = studios_df['studio'].astype(pd.StringDtype())

In [456]:
themes_df.dtypes

theme    object
dtype: object

In [457]:
themes_df['theme'] = themes_df['theme'].astype(pd.StringDtype())

fetching the movies without a name

In [458]:
movies_df[movies_df['name'].isna()]

name  date tagline  \
id                            
1287515  <NA>  2015    <NA>   
1617643  <NA>  <NA>    <NA>   
1646521  <NA>  2008    <NA>   
1648186  <NA>  <NA>    <NA>   
1720295  <NA>  <NA>    <NA>   
1725370  <NA>  <NA>    <NA>   
1741482  <NA>  <NA>    <NA>   
1840338  <NA>  <NA>    <NA>   
1883229  <NA>  <NA>    <NA>   
1894772  <NA>  <NA>    <NA>   

                                               description  minute  rating  
id                                                                          
1287515  NONE is a short film that explores the balance...     4.0     NaN  
1617643                                               <NA>     NaN     NaN  
1646521                                               <NA>     NaN     NaN  
1648186                                               <NA>     NaN     NaN  
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN  
1725370                                               <NA>     NaN     NaN  
1741482                                               <NA>    90.0     NaN  
1840338                                               <NA>     NaN     NaN  
1883229                                               <NA>     NaN     NaN  
1894772                                               <NA>     NaN     NaN

### Movies:

by joining the subset of the movie without a name we can ensure that no reference are lost during the process (no other part of the dataset actually contain some data about those movies)

In [459]:
movies_na_subset = pd.DataFrame(movies_df[movies_df['name'].isna()])

#movies_na_subset join actors
movies_na_subset.join(actors_df, on='id', lsuffix='_movies', rsuffix='_actors')

name_movies  date tagline  \
id                                  
1287515        <NA>  2015    <NA>   
1617643        <NA>  <NA>    <NA>   
1646521        <NA>  2008    <NA>   
1648186        <NA>  <NA>    <NA>   
1720295        <NA>  <NA>    <NA>   
1725370        <NA>  <NA>    <NA>   
1741482        <NA>  <NA>    <NA>   
1840338        <NA>  <NA>    <NA>   
1883229        <NA>  <NA>    <NA>   
1894772        <NA>  <NA>    <NA>   

                                               description  minute  rating  \
id                                                                           
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1617643                                               <NA>     NaN     NaN   
1646521                                               <NA>     NaN     NaN   
1648186                                               <NA>     NaN     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN   
1725370                                               <NA>     NaN     NaN   
1741482                                               <NA>    90.0     NaN   
1840338                                               <NA>     NaN     NaN   
1883229                                               <NA>     NaN     NaN   
1894772                                               <NA>     NaN     NaN   

         name_actors  role  
id                          
1287515         <NA>  <NA>  
1617643         <NA>  <NA>  
1646521  Catherine R  Self  
1648186         <NA>  <NA>  
1720295         <NA>  <NA>  
1725370         <NA>  <NA>  
1741482         <NA>  <NA>  
1840338         <NA>  <NA>  
1883229         <NA>  <NA>  
1894772         <NA>  <NA>

In [460]:
#movies_na_subset join countries
movies_na_subset.join(countries_df, on='id', lsuffix='_movies', rsuffix='_countries')

name  date tagline  \
id                            
1287515  <NA>  2015    <NA>   
1617643  <NA>  <NA>    <NA>   
1646521  <NA>  2008    <NA>   
1648186  <NA>  <NA>    <NA>   
1720295  <NA>  <NA>    <NA>   
1725370  <NA>  <NA>    <NA>   
1741482  <NA>  <NA>    <NA>   
1840338  <NA>  <NA>    <NA>   
1883229  <NA>  <NA>    <NA>   
1894772  <NA>  <NA>    <NA>   

                                               description  minute  rating  \
id                                                                           
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1617643                                               <NA>     NaN     NaN   
1646521                                               <NA>     NaN     NaN   
1648186                                               <NA>     NaN     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN   
1725370                                               <NA>     NaN     NaN   
1741482                                               <NA>    90.0     NaN   
1840338                                               <NA>     NaN     NaN   
1883229                                               <NA>     NaN     NaN   
1894772                                               <NA>     NaN     NaN   

        country  
id               
1287515    <NA>  
1617643    <NA>  
1646521     USA  
1648186    <NA>  
1720295    <NA>  
1725370    <NA>  
1741482    <NA>  
1840338    <NA>  
1883229    <NA>  
1894772    <NA>

In [461]:
#movies_na_subset join crew
movies_na_subset.join(crew_df, on='id', lsuffix='_movies', rsuffix='_crew')

name_movies  date tagline  \
id                                  
1287515        <NA>  2015    <NA>   
1287515        <NA>  2015    <NA>   
1617643        <NA>  <NA>    <NA>   
1646521        <NA>  2008    <NA>   
1648186        <NA>  <NA>    <NA>   
1720295        <NA>  <NA>    <NA>   
1725370        <NA>  <NA>    <NA>   
1741482        <NA>  <NA>    <NA>   
1840338        <NA>  <NA>    <NA>   
1883229        <NA>  <NA>    <NA>   
1894772        <NA>  <NA>    <NA>   

                                               description  minute  rating  \
id                                                                           
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1617643                                               <NA>     NaN     NaN   
1646521                                               <NA>     NaN     NaN   
1648186                                               <NA>     NaN     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN   
1725370                                               <NA>     NaN     NaN   
1741482                                               <NA>    90.0     NaN   
1840338                                               <NA>     NaN     NaN   
1883229                                               <NA>     NaN     NaN   
1894772                                               <NA>     NaN     NaN   

             role         name_crew  
id                                   
1287515  Director         Ash Thorp  
1287515  Composer  Ben Lukas Boysen  
1617643      <NA>              <NA>  
1646521  Director  Giovanni De Nava  
1648186      <NA>              <NA>  
1720295      <NA>              <NA>  
1725370      <NA>              <NA>  
1741482      <NA>              <NA>  
1840338      <NA>              <NA>  
1883229      <NA>              <NA>  
1894772      <NA>              <NA>

In [462]:
#movies_na_subset join genres
movies_na_subset.join(genres_df, on='id', lsuffix='_movies', rsuffix='_genres')

name  date tagline  \
id                            
1287515  <NA>  2015    <NA>   
1617643  <NA>  <NA>    <NA>   
1646521  <NA>  2008    <NA>   
1648186  <NA>  <NA>    <NA>   
1720295  <NA>  <NA>    <NA>   
1725370  <NA>  <NA>    <NA>   
1741482  <NA>  <NA>    <NA>   
1840338  <NA>  <NA>    <NA>   
1883229  <NA>  <NA>    <NA>   
1894772  <NA>  <NA>    <NA>   

                                               description  minute  rating  \
id                                                                           
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1617643                                               <NA>     NaN     NaN   
1646521                                               <NA>     NaN     NaN   
1648186                                               <NA>     NaN     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN   
1725370                                               <NA>     NaN     NaN   
1741482                                               <NA>    90.0     NaN   
1840338                                               <NA>     NaN     NaN   
1883229                                               <NA>     NaN     NaN   
1894772                                               <NA>     NaN     NaN   

               genre  
id                    
1287515    Animation  
1617643  Documentary  
1646521  Documentary  
1648186     Thriller  
1720295         <NA>  
1725370         <NA>  
1741482         <NA>  
1840338         <NA>  
1883229         <NA>  
1894772         <NA>

In [463]:
#movies_na_subset join languages
movies_na_subset.join(languages_df, on='id', lsuffix='_movies', rsuffix='_languages')

name  date tagline  \
id                            
1287515  <NA>  2015    <NA>   
1617643  <NA>  <NA>    <NA>   
1646521  <NA>  2008    <NA>   
1648186  <NA>  <NA>    <NA>   
1720295  <NA>  <NA>    <NA>   
1725370  <NA>  <NA>    <NA>   
1741482  <NA>  <NA>    <NA>   
1840338  <NA>  <NA>    <NA>   
1883229  <NA>  <NA>    <NA>   
1894772  <NA>  <NA>    <NA>   

                                               description  minute  rating  \
id                                                                           
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1617643                                               <NA>     NaN     NaN   
1646521                                               <NA>     NaN     NaN   
1648186                                               <NA>     NaN     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN   
1725370                                               <NA>     NaN     NaN   
1741482                                               <NA>    90.0     NaN   
1840338                                               <NA>     NaN     NaN   
1883229                                               <NA>     NaN     NaN   
1894772                                               <NA>     NaN     NaN   

             type language  
id                          
1287515      <NA>     <NA>  
1617643  Language  English  
1646521  Language  English  
1648186  Language  English  
1720295  Language  Burmese  
1725370  Language  English  
1741482  Language  English  
1840338  Language  English  
1883229  Language  English  
1894772  Language  English

In [464]:
#movies_na_subset join posters
movies_na_subset.join(posters_df, on='id', lsuffix='_movies', rsuffix='_posters')

name  date tagline  \
id                            
1287515  <NA>  2015    <NA>   
1617643  <NA>  <NA>    <NA>   
1646521  <NA>  2008    <NA>   
1648186  <NA>  <NA>    <NA>   
1720295  <NA>  <NA>    <NA>   
1725370  <NA>  <NA>    <NA>   
1741482  <NA>  <NA>    <NA>   
1840338  <NA>  <NA>    <NA>   
1883229  <NA>  <NA>    <NA>   
1894772  <NA>  <NA>    <NA>   

                                               description  minute  rating  \
id                                                                           
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1617643                                               <NA>     NaN     NaN   
1646521                                               <NA>     NaN     NaN   
1648186                                               <NA>     NaN     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN   
1725370                                               <NA>     NaN     NaN   
1741482                                               <NA>    90.0     NaN   
1840338                                               <NA>     NaN     NaN   
1883229                                               <NA>     NaN     NaN   
1894772                                               <NA>     NaN     NaN   

                                                      link  
id                                                          
1287515  https://a.ltrbxd.com/resized/film-poster/4/4/7...  
1617643                                               <NA>  
1646521  https://a.ltrbxd.com/resized/film-poster/1/0/1...  
1648186                                               <NA>  
1720295                                               <NA>  
1725370                                               <NA>  
1741482  https://a.ltrbxd.com/resized/film-poster/6/5/6...  
1840338  https://a.ltrbxd.com/resized/film-poster/5/8/4...  
1883229  https://a.ltrbxd.com/resized/film-poster/7/4/1...  
1894772  https://a.ltrbxd.com/resized/film-poster/1/0/4...

In [465]:
#movies_na_subset join releases
movies_na_subset.join(releases_df, on='id', lsuffix='_movies', rsuffix='_releases')

name  date_movies tagline  \
id                                   
1287515  <NA>         2015    <NA>   
1617643  <NA>         <NA>    <NA>   
1646521  <NA>         2008    <NA>   
1648186  <NA>         <NA>    <NA>   
1720295  <NA>         <NA>    <NA>   
1725370  <NA>         <NA>    <NA>   
1741482  <NA>         <NA>    <NA>   
1840338  <NA>         <NA>    <NA>   
1883229  <NA>         <NA>    <NA>   
1894772  <NA>         <NA>    <NA>   

                                               description  minute  \
id                                                                   
1287515  NONE is a short film that explores the balance...     4.0   
1617643                                               <NA>     NaN   
1646521                                               <NA>     NaN   
1648186                                               <NA>     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0   
1725370                                               <NA>     NaN   
1741482                                               <NA>    90.0   
1840338                                               <NA>     NaN   
1883229                                               <NA>     NaN   
1894772                                               <NA>     NaN   

         rating_movies country date_releases        type rating_releases  
id                                                                        
1287515            NaN     USA    2015-01-01  Theatrical            <NA>  
1617643            NaN    <NA>          <NA>        <NA>            <NA>  
1646521            NaN     USA    2008-03-02  Theatrical              PG  
1648186            NaN    <NA>          <NA>        <NA>            <NA>  
1720295            NaN    <NA>          <NA>        <NA>            <NA>  
1725370            NaN    <NA>          <NA>        <NA>            <NA>  
1741482            NaN    <NA>          <NA>        <NA>            <NA>  
1840338            NaN    <NA>          <NA>        <NA>            <NA>  
1883229            NaN    <NA>          <NA>        <NA>            <NA>  
1894772            NaN    <NA>          <NA>        <NA>            <NA>

In [466]:
#movies_na_subset join studios
movies_na_subset.join(studios_df, on='id', lsuffix='_movies', rsuffix='_studios')

name  date tagline  \
id                            
1287515  <NA>  2015    <NA>   
1617643  <NA>  <NA>    <NA>   
1646521  <NA>  2008    <NA>   
1648186  <NA>  <NA>    <NA>   
1720295  <NA>  <NA>    <NA>   
1725370  <NA>  <NA>    <NA>   
1741482  <NA>  <NA>    <NA>   
1840338  <NA>  <NA>    <NA>   
1883229  <NA>  <NA>    <NA>   
1894772  <NA>  <NA>    <NA>   

                                               description  minute  rating  \
id                                                                           
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1617643                                               <NA>     NaN     NaN   
1646521                                               <NA>     NaN     NaN   
1648186                                               <NA>     NaN     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN   
1725370                                               <NA>     NaN     NaN   
1741482                                               <NA>    90.0     NaN   
1840338                                               <NA>     NaN     NaN   
1883229                                               <NA>     NaN     NaN   
1894772                                               <NA>     NaN     NaN   

        studio  
id              
1287515   <NA>  
1617643   <NA>  
1646521   <NA>  
1648186   <NA>  
1720295   <NA>  
1725370   <NA>  
1741482   <NA>  
1840338   <NA>  
1883229   <NA>  
1894772   <NA>

In [467]:
#movies_na_subset join themes
movies_na_subset.join(themes_df, on='id', lsuffix='_movies', rsuffix='_themes')

name  date tagline  \
id                            
1287515  <NA>  2015    <NA>   
1617643  <NA>  <NA>    <NA>   
1646521  <NA>  2008    <NA>   
1648186  <NA>  <NA>    <NA>   
1720295  <NA>  <NA>    <NA>   
1725370  <NA>  <NA>    <NA>   
1741482  <NA>  <NA>    <NA>   
1840338  <NA>  <NA>    <NA>   
1883229  <NA>  <NA>    <NA>   
1894772  <NA>  <NA>    <NA>   

                                               description  minute  rating  \
id                                                                           
1287515  NONE is a short film that explores the balance...     4.0     NaN   
1617643                                               <NA>     NaN     NaN   
1646521                                               <NA>     NaN     NaN   
1648186                                               <NA>     NaN     NaN   
1720295  In this directorial debut of Eden Ewardson, he...     8.0     NaN   
1725370                                               <NA>     NaN     NaN   
1741482                                               <NA>    90.0     NaN   
1840338                                               <NA>     NaN     NaN   
1883229                                               <NA>     NaN     NaN   
1894772                                               <NA>     NaN     NaN   

        theme  
id             
1287515  <NA>  
1617643  <NA>  
1646521  <NA>  
1648186  <NA>  
1720295  <NA>  
1725370  <NA>  
1741482  <NA>  
1840338  <NA>  
1883229  <NA>  
1894772  <NA>

## Looking at the joined table it is possible to make some correction at the dataset

movie with id 1287515: looking at the description and at the poster and after a quick search on internet it is possible to evaluate that the name of the Movie is ***NONE***, no it is possible to update the name in the table

In [468]:
display(Image(url=posters_df['link'][1287515], width=200, height=300))

In [469]:
movies_df.loc[1287515,'name'] = "NONE"

movie with id: 1720295 looking at the description and after a quick search on internet it is possible to evaluate that the name of the Movie is ***Memorandum of Softness Green***

In [470]:
movies_df.loc[1720295, 'name'] = "Memorandum of Softness Green"

movie with id 1741482: looking at the poster it is possible to name the movie: ***Sweethurt*** but this time the record for this movie is a duplicate (see 1254818) so all the reference will be deleted

In [471]:
movies_df.drop(1720295)
actors_df.drop(1720295, errors='ignore')
countries_df.drop(1720295, errors='ignore')
crew_df.drop(1720295, errors='ignore')
genres_df.drop(1720295, errors='ignore')
languages_df.drop(1720295, errors='ignore')
posters_df.drop(1720295, errors='ignore')
releases_df.drop(1720295, errors='ignore')
studios_df.drop(1720295, errors='ignore')
themes_df.drop(1720295, errors='ignore')
print()

movie with id 1840338: looking at the poster it is possible to name the movie: ***The Find*** and the director is ***Daniel Dahlstrom***

In [472]:
display(Image(url=posters_df['link'][1840338], width=200, height=300))

In [473]:
movies_df.loc[1840338,'name'] = "The Find"
crew_df.loc[1840338] = ['Director'] + ["Daniel Dahlstrom"]

movies with id: 1617643,1646521,1648186,1725370,1741482,1883229,1894772 will be deleted along with every reference

In [474]:
#multiple execution of this block could bring some errors
movies_df = movies_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772]).copy()
actors_df = actors_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
countries_df = countries_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
crew_df = crew_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
genres_df = genres_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
languages_df = languages_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
posters_df = posters_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
releases_df = releases_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
studios_df = studios_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
themes_df = themes_df.drop([1617643,1646521,1648186,1725370,1741482,1883229,1894772], errors='ignore').copy()
print()

In [475]:
movies_df[movies_df['name'].isna()]

Empty DataFrame
Columns: [name, date, tagline, description, minute, rating]
Index: []

in the dataset there are movies with same name, and description but different minute and rating. it's not safe to delete duplicate that are not equal in every column of the dataset because a movies may have been produced in different versions

In [476]:
movies_df.loc[movies_df.duplicated(subset=['name','date','description','minute','rating'])]

name  date  \
id                                           
1073819              Better Than Sex  2000   
1073820                     Amoklauf  1994   
1073822         Still Working 9 to 5  2022   
1073823  Power On: The Story of Xbox  2021   
1073824            Crossing the Line  2006   
...                              ...   ...   
1940234                         Medo  2023   
1940448   Riina - Le verità nascoste  2018   
1940456                 Yen Ching 燕京  2018   
1940593              Happy Birthday!  2013   
1941150                     Extraños  <NA>   

                                                  tagline  \
id                                                          
1073819            3 days in the life of a 1 night stand.   
1073820                                              <NA>   
1073822                                              <NA>   
1073823  Four gamers. One idea. And a billion dollar bet.   
1073824                                              <NA>   
...                                                   ...   
1940234                                              <NA>   
1940448                                              <NA>   
1940456                                              <NA>   
1940593                                              <NA>   
1941150                                              <NA>   

                                               description  minute  rating  
id                                                                          
1073819  After a one-night stand a couple is faced with...    84.0    3.24  
1073820  A nameless waiter spends his days sitting arou...    65.0     NaN  
1073822  Examines the 40-year evolution of gender inequ...    95.0     NaN  
1073823  Xbox almost didn't happen. Find out why in thi...     NaN    3.61  
1073824  In 1962, a U.S. soldier sent to guard the peac...    94.0    3.44  
...                                                    ...     ...     ...  
1940234                                               <NA>     4.0     NaN  
1940448                                               <NA>    45.0     NaN  
1940456  An intergenerational dilemma between immigrant...    64.0     NaN  
1940593  'Misery' doesn't like 'company' -- but 'compan...    20.0     NaN  
1941150                                               <NA>     NaN     NaN  

[4115 rows x 6 columns]

removing the duplicates

In [477]:
movies_df = movies_df.loc[~movies_df.duplicated(subset=['name','date','description','minute','rating'])].copy()
number_of_duplicate = movies_df.duplicated(subset=['name','date','description','minute','rating']).sum()
print("Number of duplicates:" ,number_of_duplicate)

Number of duplicates: 0


### Actors

In [478]:
actors_df

name                 role
id                                             
1000001      Margot Robbie               Barbie
1000001       Ryan Gosling                  Ken
1000001    America Ferrera               Gloria
1000001  Ariana Greenblatt                Sasha
1000001           Issa Rae               Barbie
...                    ...                  ...
1941596            Marc Ma            Ba Cai/巴莱
1941596                线雨轩              Tata/塔塔
1941596       Jiang Yixuan  Zuo Yila（Zoila）/佐伊拉
1941597     Hiroshi Mikami                 <NA>
1941597      Keiko Oginome                 <NA>

[5798449 rows x 2 columns]

In [479]:
actors_df.loc[actors_df['name'].isna()]

name            role
id                           
1443629  <NA>            <NA>
1469981  <NA>            Self
1474958  <NA>  Cinematography
1773264  <NA>            <NA>

there is no way to reach these names

In [480]:
actors_df = actors_df.loc[~actors_df['name'].isna()].copy()
actors_df

name                 role
id                                             
1000001      Margot Robbie               Barbie
1000001       Ryan Gosling                  Ken
1000001    America Ferrera               Gloria
1000001  Ariana Greenblatt                Sasha
1000001           Issa Rae               Barbie
...                    ...                  ...
1941596            Marc Ma            Ba Cai/巴莱
1941596                线雨轩              Tata/塔塔
1941596       Jiang Yixuan  Zuo Yila（Zoila）/佐伊拉
1941597     Hiroshi Mikami                 <NA>
1941597      Keiko Oginome                 <NA>

[5798445 rows x 2 columns]

In [481]:
actors_df.duplicated(subset=['name']).count()

np.int64(5798445)

In [482]:
countries_df

country
id                  
1000001           UK
1000001          USA
1000002  South Korea
1000003          USA
1000004      Germany
...              ...
1941593        China
1941594          USA
1941595          USA
1941596        China
1941597        Japan

[693475 rows x 1 columns]

In [483]:
countries_df.loc[countries_df['country'].isna()]

Empty DataFrame
Columns: [country]
Index: []

countries have a lot of duplicates because each movie could have been  recorded in one or more countries, there is no need to delete duplicates is this case

In [484]:
crew_df

role                  name
id                                           
1000001        Director          Greta Gerwig
1000001        Producer          Tom Ackerley
1000001        Producer         Margot Robbie
1000001        Producer        Robbie Brenner
1000001        Producer          David Heyman
...                 ...                   ...
1941596          Editor  Eric Kwong Chi-Leung
1941596  Cinematography             Kenny Tse
1941596        Composer                   胡小欧
1941596  Costume design           Kenneth Yee
1840338        Director      Daniel Dahlstrom

[4720183 rows x 2 columns]

In [485]:
crew_df.loc[crew_df['name'].isna()]

role  name
id                   
1859397  Writer  <NA>

In [486]:
crew_df = crew_df[~crew_df['name'].isna()]

dataframe crew have a lot of duplicates because each crew member participated in multiple movies

In [489]:
crew_df.loc[crew_df.duplicated()]

role                  name
id                                            
1000005  Camera operator           Ari Robbins
1000005           Stunts          Danny Downey
1000005            Sound           Ai-Ling Lee
1000005            Sound         Dan O'Connell
1000005      Hairstyling       Fríða Aradóttir
...                  ...                   ...
1941596          Casting                   线雨轩
1941596           Editor  Eric Kwong Chi-Leung
1941596   Cinematography             Kenny Tse
1941596   Costume design           Kenneth Yee
1840338         Director      Daniel Dahlstrom

[2907770 rows x 2 columns]